/**
 * @agentlog/backend — Commit 上下文与解释服务
 *
 * 职责：
 *  1. 生成 Commit 的上下文文档（Markdown / JSON / XML），
 *     可直接作为新 AI 对话的上下文注入。
 *  2. 生成 Commit 的解释摘要，概括 AI 交互的要点。
 */

import type {
  AgentSession,
  CommitContextOptions,
  CommitContextResult,
  CommitExplainResult,
  ContextFormat,
  ContextSessionItem,
  ExportLanguage,
  SessionExplainItem,
} from "@agentlog/shared";
import { getSessionsByCommitHash, getSessionById } from "./logService";
import { getCommitInfo } from "./gitService";
import { getDatabase, fromJson, type CommitRow } from "../db/database";

// ─────────────────────────────────────────────
// 默认值
// ─────────────────────────────────────────────

const DEFAULT_OPTIONS: Required<CommitContextOptions> = {
  format: "markdown",
  language: "zh",
  includePrompts: true,
  includeResponses: true,
  includeReasoning: true,
  includeChangedFiles: true,
  maxContentLength: 2000,
  maxSessions: 0,
};

// ─────────────────────────────────────────────
// 国际化
// ─────────────────────────────────────────────

const contextI18n = {
  zh: {
    title: "📋 Commit 上下文文档",
    commitInfo: "## 提交信息",
    hash: "Hash",
    message: "提交说明",
    author: "提交者",
    time: "时间",
    changedFiles: "## 变更文件",
    aiSessions: "## AI 交互记录",
    sessionIndex: "### 会话",
    model: "模型",
    source: "来源",
    provider: "提供商",
    prompt: "📝 Prompt",
    reasoning: "💭 推理过程",
    response: "🤖 Response",
    affectedFiles: "涉及文件",
    tags: "标签",
    note: "备注",
    duration: "耗时",
    noSessions: "> 此 Commit 没有关联的 AI 交互记录。",
    usageHint: "## 💡 使用提示",
    usageHintContent:
      "本文档可直接作为新 AI 对话的上下文，帮助 AI 理解此次提交的历史决策和变更背景。",
    generatedAt: "生成时间",
    generatedBy: "由 AgentLog 自动生成",
    truncated: "…（已截断）",
    totalSessions: "关联会话数",
    ms: "毫秒",
  },
  en: {
    title: "📋 Commit Context Document",
    commitInfo: "## Commit Information",
    hash: "Hash",
    message: "Message",
    author: "Author",
    time: "Time",
    changedFiles: "## Changed Files",
    aiSessions: "## AI Interaction Records",
    sessionIndex: "### Session",
    model: "Model",
    source: "Source",
    provider: "Provider",
    prompt: "📝 Prompt",
    reasoning: "💭 Reasoning",
    response: "🤖 Response",
    affectedFiles: "Affected Files",
    tags: "Tags",
    note: "Note",
    duration: "Duration",
    noSessions: "> No AI interaction records found for this commit.",
    usageHint: "## 💡 Usage Hint",
    usageHintContent:
      "This document can be used directly as context for a new AI conversation, helping the AI understand the historical decisions and changes behind this commit.",
    generatedAt: "Generated At",
    generatedBy: "Auto-generated by AgentLog",
    truncated: "…(truncated)",
    totalSessions: "AI Sessions",
    ms: "ms",
  },
} as const;

const explainI18n = {
  zh: {
    title: "📖 Commit AI 交互解释",
    commitInfo: "## 提交信息",
    hash: "Hash",
    message: "提交说明",
    author: "提交者",
    time: "时间",
    overallSummary: "## 总体概述",
    sessionDetails: "## 会话详情",
    sessionIndex: "###",
    model: "模型",
    source: "来源",
    timeLabel: "时间",
    promptSummary: "用户意图",
    responseSummary: "AI 回应",
    hasReasoning: "推理过程",
    yes: "✅ 包含",
    no: "❌ 无",
    affectedFiles: "涉及文件",
    allAffectedFiles: "## 涉及文件汇总",
    tags: "标签",
    generatedAt: "生成时间",
    generatedBy: "由 AgentLog 自动生成",
    noSessions: "此 Commit 没有关联的 AI 交互记录。",
    summaryTemplate: (count: number, models: string[], files: number) =>
      `本次提交共关联 **${count}** 次 AI 交互会话，使用了 ${models.map((m) => `\`${m}\``).join("、")} 等模型，涉及 **${files}** 个文件的变更。`,
    summaryNoSession: "本次提交未关联任何 AI 交互会话。",
  },
  en: {
    title: "📖 Commit AI Interaction Explanation",
    commitInfo: "## Commit Information",
    hash: "Hash",
    message: "Message",
    author: "Author",
    time: "Time",
    overallSummary: "## Overall Summary",
    sessionDetails: "## Session Details",
    sessionIndex: "###",
    model: "Model",
    source: "Source",
    timeLabel: "Time",
    promptSummary: "User Intent",
    responseSummary: "AI Response",
    hasReasoning: "Reasoning",
    yes: "✅ Included",
    no: "❌ None",
    affectedFiles: "Affected Files",
    allAffectedFiles: "## All Affected Files",
    tags: "Tags",
    generatedAt: "Generated At",
    generatedBy: "Auto-generated by AgentLog",
    noSessions: "No AI interaction records found for this commit.",
    summaryTemplate: (count: number, models: string[], files: number) =>
      `This commit is associated with **${count}** AI interaction session(s), using model(s) ${models.map((m) => `\`${m}\``).join(", ")}, affecting **${files}** file(s).`,
    summaryNoSession: "This commit has no associated AI interaction sessions.",
  },
} as const;

// ─────────────────────────────────────────────
// 工具函数
// ─────────────────────────────────────────────

/** 截断文本到指定长度 */
function truncate(
  text: string,
  maxLength: number,
  suffix = "…(truncated)",
): string {
  if (maxLength <= 0 || text.length <= maxLength) return text;
  return text.slice(0, maxLength) + suffix;
}

/** 格式化时间为可读字符串 */
function formatTime(isoStr: string): string {
  try {
    const d = new Date(isoStr);
    const pad = (n: number) => String(n).padStart(2, "0");
    return `${d.getFullYear()}-${pad(d.getMonth() + 1)}-${pad(d.getDate())} ${pad(d.getHours())}:${pad(d.getMinutes())}:${pad(d.getSeconds())}`;
  } catch {
    return isoStr;
  }
}

/** 提取文本的第一行作为摘要（最多 maxLen 字符） */
function extractSummary(text: string, maxLen = 120): string {
  if (!text) return "";
  const firstLine = text.split("\n")[0].trim();
  if (firstLine.length <= maxLen) return firstLine;
  return firstLine.slice(0, maxLen) + "…";
}

/** 聚合所有会话涉及的文件（去重排序） */
function aggregateFiles(sessions: AgentSession[]): string[] {
  const set = new Set<string>();
  for (const s of sessions) {
    for (const f of s.affectedFiles) {
      set.add(f);
    }
  }
  return [...set].sort();
}

/** 从数据库获取 CommitBinding 行（支持短 hash 前缀匹配） */
function getCommitBindingRow(commitHash: string): CommitRow | null {
  const db = getDatabase();
  const row =
    commitHash.length >= 40
      ? (db
          .prepare("SELECT * FROM commit_bindings WHERE commit_hash = ?")
          .get(commitHash) as CommitRow | undefined)
      : (db
          .prepare("SELECT * FROM commit_bindings WHERE commit_hash LIKE ?")
          .get(`${commitHash}%`) as CommitRow | undefined);
  return row ?? null;
}

/** XML 转义 */
function xmlEscape(str: string): string {
  return str
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;")
    .replace(/'/g, "&apos;");
}

/** 将 AgentSession 映射为 ContextSessionItem */
function sessionToContextItem(
  session: AgentSession,
  opts: Required<CommitContextOptions>,
): ContextSessionItem {
  return {
    sessionId: session.id,
    createdAt: session.createdAt,
    model: session.model,
    provider: session.provider,
    source: session.source,
    prompt: opts.includePrompts
      ? truncate(session.prompt, opts.maxContentLength)
      : undefined,
    reasoning:
      opts.includeReasoning && session.reasoning
        ? truncate(session.reasoning, opts.maxContentLength)
        : undefined,
    response: opts.includeResponses
      ? truncate(session.response, opts.maxContentLength)
      : undefined,
    affectedFiles: session.affectedFiles,
    tags: session.tags,
    note: session.note,
    durationMs: session.durationMs,
  };
}

/** 将 AgentSession 映射为 SessionExplainItem */
function sessionToExplainItem(session: AgentSession): SessionExplainItem {
  return {
    sessionId: session.id,
    createdAt: session.createdAt,
    model: session.model,
    source: session.source,
    promptSummary: extractSummary(session.prompt),
    responseSummary: extractSummary(session.response),
    hasReasoning: !!session.reasoning,
    affectedFiles: session.affectedFiles,
    tags: session.tags,
  };
}

// ─────────────────────────────────────────────
// 内部：解析 Commit 信息 + 会话
// ─────────────────────────────────────────────

interface ResolvedCommitData {
  resolvedHash: string;
  commitMessage: string;
  authorName: string;
  committedAt: string;
  changedFiles: string[];
  sessions: AgentSession[];
}

/**
 * 统一的 commit 数据解析逻辑，供 context / explain 共用。
 *
 * 优先从 git 获取实时信息，回退到数据库 commit_bindings 表。
 * 会话优先通过 agent_sessions.commit_hash 查询，回退到 commit_bindings.session_ids。
 */
async function resolveCommitData(
  commitHash: string,
  workspacePath?: string,
): Promise<ResolvedCommitData> {
  let commitMessage = "";
  let authorName = "";
  let committedAt = "";
  let changedFiles: string[] = [];
  let resolvedHash = commitHash;

  // 1. 优先从 git 获取 commit 元信息
  if (workspacePath) {
    try {
      const info = await getCommitInfo(workspacePath, commitHash);
      resolvedHash = info.hash;
      commitMessage = info.message;
      authorName = info.authorName;
      committedAt = info.committedAt;
      changedFiles = info.changedFiles;
    } catch {
      // git 获取失败（可能 hash 不在本仓库、或目录不是 git 仓库），回退到数据库
    }
  }

  // 2. 如果 git 未获取到，尝试从 commit_bindings 表
  if (!commitMessage) {
    const bindingRow = getCommitBindingRow(commitHash);
    if (bindingRow) {
      resolvedHash = bindingRow.commit_hash;
      commitMessage = bindingRow.message;
      authorName = bindingRow.author_name;
      committedAt = bindingRow.committed_at;
      changedFiles = fromJson<string[]>(bindingRow.changed_files, []);
    }
  }

  // 3. 获取关联的 AI 会话
  //    优先通过 agent_sessions 表的 commit_hash 字段查询
  let sessions = getSessionsByCommitHash(resolvedHash);

  //    若无结果，尝试通过 commit_bindings 表的 session_ids 逐条查找
  if (sessions.length === 0) {
    const bindingRow = getCommitBindingRow(resolvedHash);
    if (bindingRow) {
      const sessionIds = fromJson<string[]>(bindingRow.session_ids, []);
      sessions = sessionIds
        .map((id) => getSessionById(id))
        .filter((s): s is AgentSession => s !== null);
    }
  }

  return {
    resolvedHash,
    commitMessage,
    authorName,
    committedAt,
    changedFiles,
    sessions,
  };
}

// ─────────────────────────────────────────────
// 核心方法：生成 Commit 上下文
// ─────────────────────────────────────────────

/**
 * 生成指定 Commit 的上下文文档。
 *
 * 输出格式支持 Markdown / JSON / XML，可直接粘贴到新 AI 对话中作为上下文。
 *
 * @param commitHash    Git Commit Hash（完整或短 hash）
 * @param workspacePath 工作区路径（可选，用于从 git 获取实时 commit 信息）
 * @param options       上下文选项
 */
export async function generateCommitContext(
  commitHash: string,
  workspacePath?: string,
  options: CommitContextOptions = {},
): Promise<CommitContextResult> {
  const opts: Required<CommitContextOptions> = {
    ...DEFAULT_OPTIONS,
    ...options,
  };

  const data = await resolveCommitData(commitHash, workspacePath);

  // 应用 maxSessions 限制
  let { sessions } = data;
  if (opts.maxSessions > 0 && sessions.length > opts.maxSessions) {
    sessions = sessions.slice(0, opts.maxSessions);
  }

  // 构建 ContextSessionItems
  const contextItems = sessions.map((s) => sessionToContextItem(s, opts));

  // 渲染输出
  let content: string;
  switch (opts.format) {
    case "markdown":
      content = renderContextMarkdown(
        data.resolvedHash,
        data.commitMessage,
        data.authorName,
        data.committedAt,
        data.changedFiles,
        contextItems,
        opts,
      );
      break;
    case "json":
      content = renderContextJson(
        data.resolvedHash,
        data.commitMessage,
        data.authorName,
        data.committedAt,
        data.changedFiles,
        contextItems,
        opts,
      );
      break;
    case "xml":
      content = renderContextXml(
        data.resolvedHash,
        data.commitMessage,
        data.authorName,
        data.committedAt,
        data.changedFiles,
        contextItems,
        opts,
      );
      break;
    default:
      throw new Error(
        `[contextService] 不支持的上下文格式：${opts.format as string}`,
      );
  }

  return {
    commitHash: data.resolvedHash,
    commitMessage: data.commitMessage,
    authorName: data.authorName,
    committedAt: data.committedAt,
    changedFiles: opts.includeChangedFiles ? data.changedFiles : [],
    format: opts.format,
    sessionCount: contextItems.length,
    content,
    generatedAt: new Date().toISOString(),
  };
}

// ─────────────────────────────────────────────
// 核心方法：生成 Commit 解释摘要
// ─────────────────────────────────────────────

/**
 * 生成指定 Commit 的 AI 交互解释摘要。
 *
 * 输出为结构化数据 + 渲染后的 Markdown 文本，概括每条 AI 会话的用户意图和 AI 回应。
 *
 * @param commitHash    Git Commit Hash
 * @param workspacePath 工作区路径（可选）
 * @param language      输出语言，默认 'zh'
 */
export async function generateCommitExplain(
  commitHash: string,
  workspacePath?: string,
  language: ExportLanguage = "zh",
): Promise<CommitExplainResult> {
  const data = await resolveCommitData(commitHash, workspacePath);

  // 构建 SessionExplainItems
  const explainItems = data.sessions.map(sessionToExplainItem);

  // 聚合文件
  const allAffectedFiles = aggregateFiles(data.sessions);

  // 生成总体摘要
  const overallSummary = buildOverallSummary(
    data.sessions,
    allAffectedFiles,
    language,
  );

  // 渲染 Markdown
  const content = renderExplainMarkdown(
    data.resolvedHash,
    data.commitMessage,
    data.authorName,
    data.committedAt,
    overallSummary,
    explainItems,
    allAffectedFiles,
    language,
  );

  return {
    commitHash: data.resolvedHash,
    commitMessage: data.commitMessage,
    authorName: data.authorName,
    committedAt: data.committedAt,
    overallSummary,
    sessions: explainItems,
    allAffectedFiles,
    language,
    content,
    generatedAt: new Date().toISOString(),
  };
}

// ─────────────────────────────────────────────
// 总体摘要构建
// ─────────────────────────────────────────────

function buildOverallSummary(
  sessions: AgentSession[],
  allAffectedFiles: string[],
  language: ExportLanguage,
): string {
  const t = explainI18n[language];

  if (sessions.length === 0) {
    return t.summaryNoSession;
  }

  const uniqueModels = [...new Set(sessions.map((s) => s.model))];

  return t.summaryTemplate(
    sessions.length,
    uniqueModels,
    allAffectedFiles.length,
  );
}

// ─────────────────────────────────────────────
// 渲染：Markdown 上下文
// ─────────────────────────────────────────────

function renderContextMarkdown(
  commitHash: string,
  commitMessage: string,
  authorName: string,
  committedAt: string,
  changedFiles: string[],
  sessions: ContextSessionItem[],
  opts: Required<CommitContextOptions>,
): string {
  const t = contextI18n[opts.language];
  const lines: string[] = [];

  // 标题
  lines.push(`# ${t.title}`);
  lines.push("");

  // Commit 信息
  lines.push(t.commitInfo);
  lines.push("");
  lines.push(
    `| ${t.hash} | ${t.message} | ${t.author} | ${t.time} | ${t.totalSessions} |`,
  );
  lines.push("|:---|:---|:---|:---|:---|");
  lines.push(
    `| \`${commitHash.slice(0, 8)}\` | ${commitMessage || "-"} | ${authorName || "-"} | ${committedAt ? formatTime(committedAt) : "-"} | ${sessions.length} |`,
  );
  lines.push("");

  // 变更文件
  if (opts.includeChangedFiles && changedFiles.length > 0) {
    lines.push(t.changedFiles);
    lines.push("");
    for (const f of changedFiles) {
      lines.push(`- \`${f}\``);
    }
    lines.push("");
  }

  // AI 交互记录
  lines.push(t.aiSessions);
  lines.push("");

  if (sessions.length === 0) {
    lines.push(t.noSessions);
    lines.push("");
  } else {
    sessions.forEach((item, idx) => {
      renderContextSessionMarkdown(item, idx, t, lines);
    });
  }

  // 使用提示
  lines.push(t.usageHint);
  lines.push("");
  lines.push(t.usageHintContent);
  lines.push("");

  // 页脚
  lines.push("---");
  lines.push(
    `<sub>${t.generatedBy} | ${t.generatedAt}: ${formatTime(new Date().toISOString())}</sub>`,
  );

  return lines.join("\n");
}

/** 渲染单条会话的 Markdown 块 */
function renderContextSessionMarkdown(
  item: ContextSessionItem,
  idx: number,
  t: (typeof contextI18n)[ExportLanguage],
  lines: string[],
): void {
  const shortId = item.sessionId.slice(0, 8);

  lines.push(`${t.sessionIndex} #${idx + 1} <sub>\`${shortId}\`</sub>`);
  lines.push("");

  // 元数据表格
  lines.push(
    `| ${t.model} | ${t.source} | ${t.provider} | ${t.time} | ${t.duration} |`,
  );
  lines.push("|:---|:---|:---|:---|:---|");
  lines.push(
    `| \`${item.model}\` | \`${item.source}\` | \`${item.provider}\` | ${formatTime(item.createdAt)} | ${item.durationMs}${t.ms} |`,
  );
  lines.push("");

  // Prompt
  if (item.prompt) {
    lines.push(`**${t.prompt}**`);
    lines.push("");
    lines.push(`> ${item.prompt.replace(/\n/g, "\n> ")}`);
    lines.push("");
  }

  // Reasoning
  if (item.reasoning) {
    lines.push(`**${t.reasoning}**`);
    lines.push("");
    lines.push("<details>");
    lines.push(`<summary>${t.reasoning}</summary>`);
    lines.push("");
    lines.push(item.reasoning);
    lines.push("");
    lines.push("</details>");
    lines.push("");
  }

  // Response
  if (item.response) {
    lines.push(`**${t.response}**`);
    lines.push("");
    lines.push(`> ${item.response.replace(/\n/g, "\n> ")}`);
    lines.push("");
  }

  // 涉及文件
  if (item.affectedFiles.length > 0) {
    lines.push(
      `**${t.affectedFiles}**：${item.affectedFiles.map((f) => `\`${f}\``).join(" · ")}`,
    );
    lines.push("");
  }

  // 标签
  if (item.tags && item.tags.length > 0) {
    lines.push(
      `**${t.tags}**：${item.tags.map((tag) => `\`${tag}\``).join(" ")}`,
    );
    lines.push("");
  }

  // 备注
  if (item.note) {
    lines.push(`**${t.note}**：${item.note}`);
    lines.push("");
  }

  lines.push("---");
  lines.push("");
}

// ─────────────────────────────────────────────
// 渲染：JSON 上下文
// ─────────────────────────────────────────────

function renderContextJson(
  commitHash: string,
  commitMessage: string,
  authorName: string,
  committedAt: string,
  changedFiles: string[],
  sessions: ContextSessionItem[],
  opts: Required<CommitContextOptions>,
): string {
  const doc = {
    _type: "agentlog-commit-context",
    _version: "1.0",
    commit: {
      hash: commitHash,
      shortHash: commitHash.slice(0, 8),
      message: commitMessage,
      author: authorName,
      committedAt,
      changedFiles: opts.includeChangedFiles ? changedFiles : undefined,
    },
    sessionCount: sessions.length,
    sessions: sessions.map((item) => ({
      sessionId: item.sessionId,
      createdAt: item.createdAt,
      model: item.model,
      provider: item.provider,
      source: item.source,
      durationMs: item.durationMs,
      prompt: item.prompt,
      reasoning: item.reasoning,
      response: item.response,
      affectedFiles:
        item.affectedFiles.length > 0 ? item.affectedFiles : undefined,
      tags: item.tags && item.tags.length > 0 ? item.tags : undefined,
      note: item.note || undefined,
    })),
    generatedAt: new Date().toISOString(),
    generatedBy: "AgentLog",
  };

  return JSON.stringify(doc, null, 2);
}

// ─────────────────────────────────────────────
// 渲染：XML 上下文
// ─────────────────────────────────────────────

function renderContextXml(
  commitHash: string,
  commitMessage: string,
  authorName: string,
  committedAt: string,
  changedFiles: string[],
  sessions: ContextSessionItem[],
  opts: Required<CommitContextOptions>,
): string {
  const lines: string[] = [];

  lines.push('<?xml version="1.0" encoding="UTF-8"?>');
  lines.push('<agentlog-commit-context version="1.0" generatedBy="AgentLog">');

  // Commit 信息
  lines.push("  <commit>");
  lines.push(`    <hash>${xmlEscape(commitHash)}</hash>`);
  lines.push(`    <shortHash>${xmlEscape(commitHash.slice(0, 8))}</shortHash>`);
  lines.push(`    <message>${xmlEscape(commitMessage)}</message>`);
  lines.push(`    <author>${xmlEscape(authorName)}</author>`);
  lines.push(`    <committedAt>${xmlEscape(committedAt)}</committedAt>`);

  if (opts.includeChangedFiles && changedFiles.length > 0) {
    lines.push("    <changedFiles>");
    for (const f of changedFiles) {
      lines.push(`      <file>${xmlEscape(f)}</file>`);
    }
    lines.push("    </changedFiles>");
  }
  lines.push("  </commit>");

  // 会话
  lines.push(`  <sessions count="${sessions.length}">`);
  for (const item of sessions) {
    lines.push(`    <session id="${xmlEscape(item.sessionId)}">`);
    lines.push(`      <createdAt>${xmlEscape(item.createdAt)}</createdAt>`);
    lines.push(`      <model>${xmlEscape(item.model)}</model>`);
    lines.push(`      <provider>${xmlEscape(item.provider)}</provider>`);
    lines.push(`      <source>${xmlEscape(item.source)}</source>`);
    lines.push(`      <durationMs>${item.durationMs}</durationMs>`);

    if (item.prompt) {
      lines.push(`      <prompt><![CDATA[${item.prompt}]]></prompt>`);
    }
    if (item.reasoning) {
      lines.push(`      <reasoning><![CDATA[${item.reasoning}]]></reasoning>`);
    }
    if (item.response) {
      lines.push(`      <response><![CDATA[${item.response}]]></response>`);
    }

    if (item.affectedFiles.length > 0) {
      lines.push("      <affectedFiles>");
      for (const f of item.affectedFiles) {
        lines.push(`        <file>${xmlEscape(f)}</file>`);
      }
      lines.push("      </affectedFiles>");
    }

    if (item.tags && item.tags.length > 0) {
      lines.push("      <tags>");
      for (const tag of item.tags) {
        lines.push(`        <tag>${xmlEscape(tag)}</tag>`);
      }
      lines.push("      </tags>");
    }

    if (item.note) {
      lines.push(`      <note>${xmlEscape(item.note)}</note>`);
    }

    lines.push("    </session>");
  }
  lines.push("  </sessions>");

  lines.push(`  <generatedAt>${new Date().toISOString()}</generatedAt>`);
  lines.push("</agentlog-commit-context>");

  return lines.join("\n");
}

// ─────────────────────────────────────────────
// 渲染：Markdown 解释摘要
// ─────────────────────────────────────────────

function renderExplainMarkdown(
  commitHash: string,
  commitMessage: string,
  authorName: string,
  committedAt: string,
  overallSummary: string,
  sessions: SessionExplainItem[],
  allAffectedFiles: string[],
  language: ExportLanguage,
): string {
  const t = explainI18n[language];
  const lines: string[] = [];

  // 标题
  lines.push(`# ${t.title}`);
  lines.push("");

  // Commit 信息
  lines.push(t.commitInfo);
  lines.push("");
  lines.push(`| ${t.hash} | ${t.message} | ${t.author} | ${t.time} |`);
  lines.push("|:---|:---|:---|:---|");
  lines.push(
    `| \`${commitHash.slice(0, 8)}\` | ${commitMessage || "-"} | ${authorName || "-"} | ${committedAt ? formatTime(committedAt) : "-"} |`,
  );
  lines.push("");

  // 总体概述
  lines.push(t.overallSummary);
  lines.push("");
  lines.push(overallSummary);
  lines.push("");

  // 会话详情
  if (sessions.length > 0) {
    lines.push(t.sessionDetails);
    lines.push("");

    sessions.forEach((item, idx) => {
      const shortId = item.sessionId.slice(0, 8);
      lines.push(`${t.sessionIndex} ${idx + 1}. <sub>\`${shortId}\`</sub>`);
      lines.push("");

      // 元数据表格
      lines.push(
        `| ${t.model} | ${t.source} | ${t.timeLabel} | ${t.hasReasoning} |`,
      );
      lines.push("|:---|:---|:---|:---|");
      lines.push(
        `| \`${item.model}\` | \`${item.source}\` | ${formatTime(item.createdAt)} | ${item.hasReasoning ? t.yes : t.no} |`,
      );
      lines.push("");

      // 用户意图
      lines.push(`**${t.promptSummary}**：${item.promptSummary || "-"}`);
      lines.push("");

      // AI 回应
      lines.push(`**${t.responseSummary}**：${item.responseSummary || "-"}`);
      lines.push("");

      // 涉及文件
      if (item.affectedFiles.length > 0) {
        lines.push(
          `**${t.affectedFiles}**：${item.affectedFiles.map((f) => `\`${f}\``).join(" · ")}`,
        );
        lines.push("");
      }

      // 标签
      if (item.tags && item.tags.length > 0) {
        lines.push(
          `**${t.tags}**：${item.tags.map((tag) => `\`${tag}\``).join(" ")}`,
        );
        lines.push("");
      }

      lines.push("---");
      lines.push("");
    });
  } else {
    lines.push(`> ${t.noSessions}`);
    lines.push("");
  }

  // 涉及文件汇总
  if (allAffectedFiles.length > 0) {
    lines.push(t.allAffectedFiles);
    lines.push("");
    for (const f of allAffectedFiles) {
      lines.push(`- \`${f}\``);
    }
    lines.push("");
  }

  // 页脚
  lines.push("---");
  lines.push(
    `<sub>${t.generatedBy} | ${t.generatedAt}: ${formatTime(new Date().toISOString())}</sub>`,
  );

  return lines.join("\n");
}
