/**
 * @agentlog/backend — 导出服务
 *
 * 职责：将 AgentSession 数据渲染为各类可读文档：
 *  - weekly-report  : 中/英文周报（Markdown）
 *  - pr-description : PR / Code Review 说明（Markdown）
 *  - jsonl          : 原始 JSONL（逐行 JSON）
 *  - csv            : 结构化 CSV 表格
 */

import type {
  AgentSession,
  ExportFormat,
  ExportLanguage,
  ExportOptions,
  ExportResult,
  SessionQueryFilter,
} from '@agentlog/shared';
import { querySessions, exportSessionsAsJsonl } from './logService';

// ─────────────────────────────────────────────
// 主入口
// ─────────────────────────────────────────────

/**
 * 根据 ExportOptions 生成对应格式的导出内容。
 */
export async function exportSessions(
  options: ExportOptions,
): Promise<ExportResult> {
  const {
    format,
    startDate,
    endDate,
    language = 'zh',
    tags,
    workspacePath,
    onlyBoundToCommit,
  } = options;

  // 构建查询过滤器（不分页，全量导出）
  const filter: SessionQueryFilter = {
    startDate,
    endDate,
    tags,
    workspacePath,
    onlyBoundToCommit,
    page: 1,
    pageSize: 99999,
  };

  const { data: sessions, total } = querySessions(filter);
  const generatedAt = new Date().toISOString();

  let content: string;

  switch (format) {
    case 'weekly-report':
      content = renderWeeklyReport(sessions, options, language);
      break;
    case 'pr-description':
      content = renderPrDescription(sessions, options, language);
      break;
    case 'jsonl':
      content = exportSessionsAsJsonl(filter);
      break;
    case 'csv':
      content = renderCsv(sessions);
      break;
    default:
      throw new Error(`[exportService] 不支持的导出格式：${format as string}`);
  }

  return {
    format,
    content,
    sessionCount: total,
    generatedAt,
  };
}

// ─────────────────────────────────────────────
// 周报渲染
// ─────────────────────────────────────────────

const i18n = {
  zh: {
    weeklyTitle: '## AI 辅助开发周报',
    summaryHeading: '### 概览',
    totalSessions: '本周 AI 交互次数',
    boundSessions: '已关联 Commit',
    unboundSessions: '未关联 Commit',
    modelsUsed: '使用模型',
    filesChanged: '涉及文件',
    detailHeading: '### 交互详情',
    sessionIndex: '#### 交互',
    time: '时间',
    model: '模型',
    source: '来源',
    commit: '关联 Commit',
    none: '暂无',
    prompt: '**Prompt**',
    reasoning: '**推理过程（摘要）**',
    response: '**AI 回复（摘要）**',
    affectedFiles: '**涉及文件**',
    tags: '**标签**',
    note: '**备注**',
    noData: '本时间段内暂无 AI 交互记录。',
    generatedBy: '> 由 AgentLog 自动生成',
  },
  en: {
    weeklyTitle: '## AI-Assisted Development Weekly Report',
    summaryHeading: '### Summary',
    totalSessions: 'Total AI interactions',
    boundSessions: 'Bound to commit',
    unboundSessions: 'Unbound',
    modelsUsed: 'Models used',
    filesChanged: 'Files affected',
    detailHeading: '### Interaction Details',
    sessionIndex: '#### Interaction',
    time: 'Time',
    model: 'Model',
    source: 'Source',
    commit: 'Commit',
    none: 'N/A',
    prompt: '**Prompt**',
    reasoning: '**Reasoning (excerpt)**',
    response: '**Response (excerpt)**',
    affectedFiles: '**Affected Files**',
    tags: '**Tags**',
    note: '**Note**',
    noData: 'No AI interactions found in this time range.',
    generatedBy: '> Generated by AgentLog',
  },
} as const satisfies Record<ExportLanguage, Record<string, string>>;

function renderWeeklyReport(
  sessions: AgentSession[],
  options: ExportOptions,
  language: ExportLanguage,
): string {
  const t = i18n[language];
  const lines: string[] = [];

  // ── 标题 ──
  const dateRange = buildDateRangeLabel(options.startDate, options.endDate, language);
  lines.push(`${t.weeklyTitle}${dateRange ? `（${dateRange}）` : ''}`);
  lines.push('');

  if (sessions.length === 0) {
    lines.push(t.noData);
    lines.push('');
    lines.push(t.generatedBy);
    return lines.join('\n');
  }

  // ── 概览 ──
  const boundCount = sessions.filter((s) => s.commitHash).length;
  const allFiles = uniqueFiles(sessions);
  const modelSet = [...new Set(sessions.map((s) => `\`${s.model}\``))];

  lines.push(t.summaryHeading);
  lines.push('');
  lines.push(`| ${t.totalSessions} | ${t.boundSessions} | ${t.unboundSessions} | ${t.filesChanged} |`);
  lines.push(`|:---:|:---:|:---:|:---:|`);
  lines.push(
    `| ${sessions.length} | ${boundCount} | ${sessions.length - boundCount} | ${allFiles.length} |`,
  );
  lines.push('');
  lines.push(`${t.modelsUsed}：${modelSet.join('、') || t.none}`);
  lines.push('');

  // ── 按日期分组的交互详情 ──
  lines.push(t.detailHeading);
  lines.push('');

  const grouped = groupSessionsByDate(sessions);
  let globalIndex = 1;

  for (const [date, daySessions] of grouped) {
    lines.push(`#### 📅 ${date}`);
    lines.push('');

    for (const session of daySessions) {
      lines.push(...renderSessionBlock(session, globalIndex, t));
      lines.push('');
      globalIndex++;
    }
  }

  lines.push('---');
  lines.push('');
  lines.push(t.generatedBy);

  return lines.join('\n');
}

// ─────────────────────────────────────────────
// PR / Code Review 描述渲染
// ─────────────────────────────────────────────

const prI18n = {
  zh: {
    title: '## PR 说明 / 代码审查摘要',
    background: '### 背景与目标',
    backgroundDesc: '本次变更由以下 AI 辅助开发会话支持：',
    changes: '### 主要改动',
    changesDesc: '以下文件在 AI 辅助下发生了变更：',
    reasoning: '### AI 推理摘要',
    reasoningDesc: '以下是 AI 在本次开发过程中的关键推理步骤：',
    sessionRef: '**会话参考**',
    model: '模型',
    time: '时间',
    prompt: '用户提问',
    files: '涉及文件',
    noReasoning: '（该模型未提供推理过程）',
    footer: '> 本说明由 AgentLog 根据 AI 交互记录自动生成，请在提交 PR 前补充业务背景和测试说明。',
    noData: '没有找到可用于生成 PR 描述的 AI 交互记录。',
  },
  en: {
    title: '## PR Description / Code Review Summary',
    background: '### Background & Goals',
    backgroundDesc: 'This change was supported by the following AI-assisted development sessions:',
    changes: '### Key Changes',
    changesDesc: 'The following files were modified with AI assistance:',
    reasoning: '### AI Reasoning Summary',
    reasoningDesc: 'Key reasoning steps from AI during this development cycle:',
    sessionRef: '**Session Reference**',
    model: 'Model',
    time: 'Time',
    prompt: 'User prompt',
    files: 'Affected files',
    noReasoning: '(No reasoning available for this model)',
    footer: '> Auto-generated by AgentLog. Please add business context and test coverage notes before submitting the PR.',
    noData: 'No AI interaction records found to generate a PR description.',
  },
} as const satisfies Record<ExportLanguage, Record<string, string>>;

function renderPrDescription(
  sessions: AgentSession[],
  _options: ExportOptions,
  language: ExportLanguage,
): string {
  const t = prI18n[language];
  const lines: string[] = [];

  lines.push(t.title);
  lines.push('');

  if (sessions.length === 0) {
    lines.push(t.noData);
    return lines.join('\n');
  }

  // ── 背景与目标（汇总用户 Prompt） ──
  lines.push(t.background);
  lines.push('');
  lines.push(t.backgroundDesc);
  lines.push('');

  sessions.forEach((s, i) => {
    const shortId = s.id.slice(0, 8);
    const prompt = truncate(s.prompt, 200);
    lines.push(`${i + 1}. \`[${shortId}]\` ${prompt}`);
  });
  lines.push('');

  // ── 主要改动（按文件汇总） ──
  const allFiles = uniqueFiles(sessions);

  lines.push(t.changes);
  lines.push('');
  lines.push(t.changesDesc);
  lines.push('');

  if (allFiles.length > 0) {
    allFiles.forEach((f) => lines.push(`- \`${f}\``));
  } else {
    lines.push('- (no file change records)');
  }
  lines.push('');

  // ── AI 推理摘要（仅含 reasoning 的会话） ──
  const withReasoning = sessions.filter((s) => s.reasoning && s.reasoning.trim());

  if (withReasoning.length > 0) {
    lines.push(t.reasoning);
    lines.push('');
    lines.push(t.reasoningDesc);
    lines.push('');

    withReasoning.forEach((s, i) => {
      const shortId = s.id.slice(0, 8);
      lines.push(`<details>`);
      lines.push(`<summary>${i + 1}. ${t.sessionRef} <code>${shortId}</code> — ${formatTime(s.createdAt)}</summary>`);
      lines.push('');
      lines.push('```');
      lines.push(truncate(s.reasoning!, 1500));
      lines.push('```');
      lines.push('');
      lines.push(`- ${t.model}: \`${s.model}\``);
      lines.push(`- ${t.prompt}: ${truncate(s.prompt, 100)}`);
      if (s.affectedFiles.length > 0) {
        lines.push(`- ${t.files}: ${s.affectedFiles.map((f) => `\`${f}\``).join(', ')}`);
      }
      lines.push('</details>');
      lines.push('');
    });
  }

  lines.push('---');
  lines.push('');
  lines.push(t.footer);

  return lines.join('\n');
}

// ─────────────────────────────────────────────
// CSV 渲染
// ─────────────────────────────────────────────

const CSV_HEADERS = [
  'id',
  'createdAt',
  'provider',
  'model',
  'source',
  'workspacePath',
  'prompt',
  'hasReasoning',
  'responseLength',
  'commitHash',
  'affectedFiles',
  'durationMs',
  'tags',
  'note',
] as const;

function renderCsv(sessions: AgentSession[]): string {
  const rows: string[] = [CSV_HEADERS.join(',')];

  for (const s of sessions) {
    const row = [
      csvEscape(s.id),
      csvEscape(s.createdAt),
      csvEscape(s.provider),
      csvEscape(s.model),
      csvEscape(s.source),
      csvEscape(s.workspacePath),
      csvEscape(truncate(s.prompt, 500)),
      String(Boolean(s.reasoning)),
      String(s.response.length),
      csvEscape(s.commitHash ?? ''),
      csvEscape(s.affectedFiles.join(';')),
      String(s.durationMs),
      csvEscape((s.tags ?? []).join(';')),
      csvEscape(s.note ?? ''),
    ];
    rows.push(row.join(','));
  }

  return rows.join('\n');
}

// ─────────────────────────────────────────────
// 内部工具函数
// ─────────────────────────────────────────────

/** 截断字符串，超长时追加省略号 */
function truncate(str: string, maxLen: number): string {
  if (str.length <= maxLen) return str;
  return str.slice(0, maxLen) + '…';
}

/** 格式化 ISO 时间为人类可读字符串 */
function formatTime(iso: string): string {
  try {
    const d = new Date(iso);
    const pad = (n: number) => String(n).padStart(2, '0');
    return `${d.getFullYear()}-${pad(d.getMonth() + 1)}-${pad(d.getDate())} ${pad(d.getHours())}:${pad(d.getMinutes())}`;
  } catch {
    return iso;
  }
}

/** 将 ISO 日期截取为 YYYY-MM-DD */
function toDateStr(iso: string): string {
  return iso.slice(0, 10);
}

/** 按日期（YYYY-MM-DD）分组会话，返回有序 Map */
function groupSessionsByDate(
  sessions: AgentSession[],
): Map<string, AgentSession[]> {
  const map = new Map<string, AgentSession[]>();

  // 按时间正序排列，使同一天的记录按时间顺序展示
  const sorted = [...sessions].sort(
    (a, b) => new Date(a.createdAt).getTime() - new Date(b.createdAt).getTime(),
  );

  for (const session of sorted) {
    const date = toDateStr(session.createdAt);
    const group = map.get(date) ?? [];
    group.push(session);
    map.set(date, group);
  }

  return map;
}

/** 收集所有会话涉及的唯一文件列表 */
function uniqueFiles(sessions: AgentSession[]): string[] {
  const set = new Set<string>();
  for (const s of sessions) {
    for (const f of s.affectedFiles) {
      if (f) set.add(f);
    }
  }
  return [...set].sort();
}

/** 构建日期范围描述标签 */
function buildDateRangeLabel(
  startDate: string | undefined,
  endDate: string | undefined,
  language: ExportLanguage,
): string {
  if (!startDate && !endDate) return '';
  if (startDate && endDate) {
    return language === 'zh'
      ? `${startDate} ~ ${endDate}`
      : `${startDate} to ${endDate}`;
  }
  if (startDate) {
    return language === 'zh' ? `${startDate} 起` : `from ${startDate}`;
  }
  return language === 'zh' ? `截至 ${endDate}` : `until ${endDate}`;
}

/** 渲染单条 Session 的详情 Block（供周报使用） */
function renderSessionBlock(
  session: AgentSession,
  index: number,
  t: (typeof i18n)[ExportLanguage],
): string[] {
  const lines: string[] = [];
  const shortId = session.id.slice(0, 8);

  lines.push(`${t.sessionIndex} #${index} <sub>\`${shortId}\`</sub>`);
  lines.push('');

  // 元数据表格
  lines.push(
    `| ${t.time} | ${t.model} | ${t.source} | ${t.commit} |`,
  );
  lines.push(`|:---|:---|:---|:---|`);
  lines.push(
    `| ${formatTime(session.createdAt)} | \`${session.model}\` | \`${session.source}\` | ${session.commitHash ? `\`${session.commitHash.slice(0, 8)}\`` : t.none} |`,
  );
  lines.push('');

  // Prompt
  lines.push(`${t.prompt}：`);
  lines.push('');
  lines.push(`> ${truncate(session.prompt, 300).replace(/\n/g, '\n> ')}`);
  lines.push('');

  // Reasoning（若有）
  if (session.reasoning) {
    lines.push(`${t.reasoning}：`);
    lines.push('');
    lines.push('<details>');
    lines.push('<summary>展开查看推理过程</summary>');
    lines.push('');
    lines.push(truncate(session.reasoning, 800));
    lines.push('');
    lines.push('</details>');
    lines.push('');
  }

  // Response
  lines.push(`${t.response}：`);
  lines.push('');
  lines.push(`> ${truncate(session.response, 300).replace(/\n/g, '\n> ')}`);
  lines.push('');

  // 涉及文件
  if (session.affectedFiles.length > 0) {
    lines.push(
      `${t.affectedFiles}：${session.affectedFiles.map((f) => `\`${f}\``).join(' · ')}`,
    );
    lines.push('');
  }

  // 标签
  if (session.tags && session.tags.length > 0) {
    lines.push(
      `${t.tags}：${session.tags.map((tag) => `\`${tag}\``).join(' ')}`,
    );
    lines.push('');
  }

  // 备注
  if (session.note) {
    lines.push(`${t.note}：${session.note}`);
    lines.push('');
  }

  return lines;
}

/** CSV 字段转义（包裹双引号，内部双引号加倍） */
function csvEscape(value: string): string {
  const escaped = value.replace(/"/g, '""').replace(/\n/g, ' ');
  return `"${escaped}"`;
}

// ─────────────────────────────────────────────
// 导出格式列表（供前端 UI 展示用）
// ─────────────────────────────────────────────

export const EXPORT_FORMATS: Array<{
  value: ExportFormat;
  labelZh: string;
  labelEn: string;
  extension: string;
  mimeType: string;
}> = [
  {
    value: 'weekly-report',
    labelZh: '周报（Markdown）',
    labelEn: 'Weekly Report (Markdown)',
    extension: 'md',
    mimeType: 'text/markdown; charset=utf-8',
  },
  {
    value: 'pr-description',
    labelZh: 'PR / Code Review 说明（Markdown）',
    labelEn: 'PR Description (Markdown)',
    extension: 'md',
    mimeType: 'text/markdown; charset=utf-8',
  },
  {
    value: 'jsonl',
    labelZh: '原始数据（JSONL）',
    labelEn: 'Raw Data (JSONL)',
    extension: 'jsonl',
    mimeType: 'application/x-ndjson; charset=utf-8',
  },
  {
    value: 'csv',
    labelZh: '结构化表格（CSV）',
    labelEn: 'Structured Table (CSV)',
    extension: 'csv',
    mimeType: 'text/csv; charset=utf-8',
  },
];

/** 根据导出格式获取推荐文件名 */
export function suggestFilename(
  format: ExportFormat,
  language: ExportLanguage = 'zh',
): string {
  const fmt = EXPORT_FORMATS.find((f) => f.value === format);
  const ext = fmt?.extension ?? 'txt';
  const now = new Date();
  const dateStr = `${now.getFullYear()}${String(now.getMonth() + 1).padStart(2, '0')}${String(now.getDate()).padStart(2, '0')}`;
  const label = language === 'zh'
    ? { 'weekly-report': '周报', 'pr-description': 'PR说明', jsonl: '原始数据', csv: '数据表格' }[format]
    : format;
  return `agentlog_${label}_${dateStr}.${ext}`;
}
